/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiPage;

import java.sql.SQLException;
/**
 *
 * @author Lenovo
 */
//Building bluprint
class Building {
    
    String name;
    String address;
    String landmark1, landmark2, landmark3;
    Building(String name, String address, String landmark1, String landmark2, String landmark3)
    {
        this.name = name;
        this.address = address;
        this.landmark1 = landmark1; //optional field
        this.landmark2 = landmark2; //optional field
        this.landmark3 = landmark3; //optional field
    }
}
//a Building has many Rooms
class Room {
    int flatNumber;
    int area; //sqaure feet
    int rent;
    int type;
    int bathrooms;
    int maintenance;
    int electricityAccountNumber;
    Room(int flatNumber, int area, int rent, int type, int bathrooms, int maintenance, int electricityAccountNumber)
    {
        this.flatNumber = flatNumber;
        this.area = area;
        this.rent = rent;
        this.type = type;
        this.bathrooms = bathrooms;
        this.maintenance = maintenance;
        this.electricityAccountNumber = electricityAccountNumber;
    }
}

public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    
    public HomePage() {
        initComponents();

        //user code
        rooms = new java.util.ArrayList<>();
        typeButtonGroup = new javax.swing.ButtonGroup();
        typeButtonGroup.add(jRadioButton1);
        typeButtonGroup.add(jRadioButton2);
        typeButtonGroup.add(jRadioButton3);
        typeButtonGroup.add(jRadioButton4);
        this.setIconImage(createImage("/images/building.png").getImage());
        
        //establishing connection witn database
        getDatabaseConfigValues();
        while(true)
        {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                conn = (com.mysql.jdbc.Connection)java.sql.DriverManager.getConnection("jdbc:mysql://" + HOST + ":3306/" + DATABASE + "?user=" + USERNAME + "&password="+ PASSWORD);
                break;
            } 
            catch (ClassNotFoundException | SQLException ex) {
                //javax.swing.JOptionPane.showMessageDialog(null, "Database connection can not be established.\n"+ex, "Database Connection Error", javax.swing.JOptionPane.ERROR_MESSAGE);

                javax.swing.JTextField hostField = new javax.swing.JTextField(HOST);
                javax.swing.JTextField databaseField = new javax.swing.JTextField(DATABASE);
                javax.swing.JTextField userField = new javax.swing.JTextField(USERNAME);
                javax.swing.JTextField passwordField = new javax.swing.JPasswordField();
                Object[] message = {
                            "Host" , hostField,
                            "Databse", databaseField,
                            "Username", userField,
                            "Password", passwordField
                };
                int option = javax.swing.JOptionPane.showConfirmDialog(null, message, "Check/Updata your Database config value", javax.swing.JOptionPane.OK_CANCEL_OPTION);
                
                if(option == javax.swing.JOptionPane.CANCEL_OPTION) 
                     System.exit(0);
                
                HOST = hostField.getText();
                DATABASE = databaseField.getText();
                USERNAME = userField.getText();
                PASSWORD = passwordField.getText();
                
                setDataBaseConfigValues();
            }
        }
        //set Summary page
        setSummary();
    }
    private javax.swing.ImageIcon createImage(String path){
        return new javax.swing.ImageIcon(java.awt.Toolkit.getDefaultToolkit().getClass().getResource(path));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        summaryJLabel = new javax.swing.JLabel();
        addBuildingLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        roomCountJLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        buildingCountJLabel = new javax.swing.JLabel();
        addBuildingPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        landmarkJTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        landmarkJTextField2 = new javax.swing.JTextField();
        landmarkJTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        addRoomPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        roomJLabel = new javax.swing.JLabel();
        roomnoJLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rentJTextField = new javax.swing.JTextField();
        areaJTextField = new javax.swing.JTextField();
        eleaccnoJTextField = new javax.swing.JTextField();
        nextJButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        maintenanceJTextField = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        flatNoJTextField = new javax.swing.JTextField();
        bathroomJTextField = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        preJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navPanel.setBackground(new java.awt.Color(255, 255, 255));

        summaryJLabel.setBackground(new java.awt.Color(255, 255, 255));
        summaryJLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        summaryJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/note.png"))); // NOI18N
        summaryJLabel.setText(" Summary");
        summaryJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
        summaryJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                summaryJLabelMouseClicked(evt);
            }
        });

        addBuildingLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addBuildingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addBuildingLabel.setText(" Add Building");
        addBuildingLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(251, 251, 251)));
        addBuildingLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBuildingLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap(346, Short.MAX_VALUE)
                .addComponent(summaryJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBuildingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(summaryJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addBuildingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        getContentPane().add(navPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 6, 0, new java.awt.Color(0, 102, 252)));
        contentPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));

        roomCountJLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        roomCountJLabel.setText("00");
        roomCountJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel15.setText("ROOMS  IN");

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel19.setText("BUILDINGS");

        buildingCountJLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        buildingCountJLabel.setText("00");
        buildingCountJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(roomCountJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildingCountJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomCountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildingCountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        contentPanel.add(homePanel, "card4");

        addBuildingPanel.setLayout(new javax.swing.BoxLayout(addBuildingPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/building.png"))); // NOI18N
        jLabel7.setText("BUILDING");
        jLabel7.setToolTipText("");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        addBuildingPanel.add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(204, 204, 204)));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Building Name *");

        nameJTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Address *");

        addressJTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Landmark1");

        landmarkJTextField1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setText("Landmark2");

        landmarkJTextField2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        landmarkJTextField3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setText("Landmark3");

        addJButton.setBackground(new java.awt.Color(255, 255, 255));
        addJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        addJButton.setForeground(new java.awt.Color(255, 255, 255));
        addJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        addJButton.setToolTipText("Add Building");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("All * marked are required field.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(landmarkJTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landmarkJTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(landmarkJTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressJTextField)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landmarkJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landmarkJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landmarkJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addBuildingPanel.add(jPanel1);

        contentPanel.add(addBuildingPanel, "card2");

        addRoomPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        roomJLabel.setBackground(new java.awt.Color(255, 255, 255));
        roomJLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        roomJLabel.setForeground(new java.awt.Color(51, 51, 51));
        roomJLabel.setText("ROOM");

        roomnoJLabel.setBackground(new java.awt.Color(255, 255, 255));
        roomnoJLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        roomnoJLabel.setForeground(new java.awt.Color(51, 51, 51));
        roomnoJLabel.setText("  1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomnoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(roomnoJLabel)
                .addGap(0, 0, 0)
                .addComponent(roomJLabel)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        addRoomPanel.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(204, 204, 204)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        rentJTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        areaJTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        eleaccnoJTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        nextJButton.setBackground(new java.awt.Color(255, 255, 255));
        nextJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        nextJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        nextJButton.setToolTipText("Add more rooms");
        nextJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel13.setText("Flat Number *");

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel12.setText("Maintenance (INR) *");

        maintenanceJTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jRadioButton3.setText("3 BHK");
        jRadioButton3.setPreferredSize(new java.awt.Dimension(60, 25));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setText("Area (Square feet)*");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("Rent (INR) *");

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setText("Type *");

        saveJButton.setBackground(new java.awt.Color(255, 255, 255));
        saveJButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        saveJButton.setForeground(new java.awt.Color(255, 255, 255));
        saveJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveJButton.setToolTipText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel14.setText("Electricity Account Number *");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jRadioButton1.setText("1 BHK");
        jRadioButton1.setPreferredSize(new java.awt.Dimension(60, 25));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("Number of Bathrooms *");

        flatNoJTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        bathroomJTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jRadioButton2.setText("2 BHK");
        jRadioButton2.setPreferredSize(new java.awt.Dimension(60, 25));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jRadioButton4.setText("Studio");
        jRadioButton4.setPreferredSize(new java.awt.Dimension(60, 25));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("All *  marked are required field.");

        preJButton.setBackground(new java.awt.Color(255, 255, 255));
        preJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        preJButton.setToolTipText("Go Back");
        preJButton.setBorder(null);
        preJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(preJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(48, 48, 48)
                    .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(48, 48, 48)
                    .addComponent(nextJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(flatNoJTextField)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bathroomJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(areaJTextField)))
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(maintenanceJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addComponent(eleaccnoJTextField))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flatNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bathroomJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maintenanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eleaccnoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(saveJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(preJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {areaJTextField, bathroomJTextField, eleaccnoJTextField, flatNoJTextField, jRadioButton1, jRadioButton2, jRadioButton3, jRadioButton4, maintenanceJTextField, rentJTextField});

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addRoomPanel.add(jPanel6);

        contentPanel.add(addRoomPanel, "card3");

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setDataBaseConfigValues()
    {
        java.util.Properties props = new java.util.Properties();
        java.io.FileOutputStream outputFile = null;
        try
        {
            outputFile = new java.io.FileOutputStream(new java.io.File("src\\config\\config.properties"));
            
            //set values
            props.setProperty("HOST", HOST);
            props.setProperty("DATABASE", DATABASE);
            props.setProperty("USERNAME", USERNAME);
            props.setProperty("PASSWORD", PASSWORD);
            
            props.store(outputFile, "XYZ");
        }
        catch(java.io.IOException ex){
            javax.swing.JOptionPane.showMessageDialog(addRoomPanel, "config file is not found."+ ex, "IOError", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        finally {
           if(outputFile != null){
               try{
                   outputFile.close();
               }
               catch(java.io.IOException exe){
               }
           }
        }
    }
    private void getDatabaseConfigValues()
    {
        java.util.Properties props = new java.util.Properties();
        java.io.FileInputStream inputFile;
        try
        {   
            System.out.println(new java.io.File(".").getAbsolutePath());
            inputFile = new java.io.FileInputStream(new java.io.File("src\\config\\config.properties"));
            props.load(inputFile);
            
            //set config values
            HOST = props.getProperty("HOST");
            DATABASE = props.getProperty("DATABASE");
            USERNAME = props.getProperty("USERNAME");
            PASSWORD = props.getProperty("PASSWORD");
            
        }
        catch(java.io.IOException ex)
        {
            javax.swing.JOptionPane.showMessageDialog(addRoomPanel, new java.io.File(".").getAbsolutePath() + ex, "IOError", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //set summary page
    private void setSummary()
    {
        try 
        {
            //set rooms count
            String roomQuery = "SELECT COUNT(*) "
                             + "FROM room";
            java.sql.Statement roomStatement = conn.createStatement();
            java.sql.ResultSet roomResult = roomStatement.executeQuery(roomQuery);
            if(roomResult.next())
            {
                Long roomCount = roomResult.getLong("COUNT(*)");
                roomCountJLabel.setText(String.format("%2d", roomCount));
            }
            
            //set building count
            String query = "SELECT COUNT(*) "
                         + "FROM building";
            java.sql.Statement statement = conn.createStatement();
            java.sql.ResultSet result = statement.executeQuery(query);
            if(result.next())
            {
                Long buildingCount = result.getLong("COUNT(*)");
                buildingCountJLabel.setText(String.format("%2d", buildingCount));
            }
        } 
        catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Database query error.\n"+ex, "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void clearBuildingForm()
    {
        //clear Building form
        nameJTextField.setText("");
        addressJTextField.setText("");
        landmarkJTextField1.setText("");
        landmarkJTextField2.setText("");
        landmarkJTextField3.setText("");
    }
    
    private void summaryJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_summaryJLabelMouseClicked
        // TODO add your handling code here:
        if(addRoomPanel.isVisible())
        {
            int decisionValue = javax.swing.JOptionPane.showConfirmDialog(addRoomPanel, "Are you sure?\nBuilding data will lost.", "Warning", javax.swing.JOptionPane.YES_NO_OPTION ,javax.swing.JOptionPane.WARNING_MESSAGE);
            if(decisionValue == 1) return;
        }
        showSummaryPanel();
    }
    private void showSummaryPanel(){
        
        if(!homePanel.isVisible())
        {
            homePanel.setVisible(true);
            addRoomPanel.setVisible(false);
            addBuildingPanel.setVisible(false);
            
            //clear forms
            clearRoomForm();
            rooms.clear();
            roomnoJLabel.setText("  1");
            clearBuildingForm();
            setSummary();
            
            //set border
            summaryJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
            addBuildingLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(251, 251, 251)));
            
            //validate changes
            contentPanel.validate();
        }
    }//GEN-LAST:event_summaryJLabelMouseClicked

    private void addBuildingLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBuildingLabelMouseClicked
        // TODO add your handling code here:
        if(addRoomPanel.isVisible())
        {
            int decisionValue = javax.swing.JOptionPane.showConfirmDialog(addRoomPanel, "Are you sure?\nRooms data will lost.", "Warning", javax.swing.JOptionPane.YES_NO_OPTION ,javax.swing.JOptionPane.WARNING_MESSAGE);
            if(decisionValue == 1) return;
        }
        
        if(!addBuildingPanel.isVisible())
        {
            homePanel.setVisible(false);
            addRoomPanel.setVisible(false);
            addBuildingPanel.setVisible(true);
            
            //clear form 
            clearRoomForm();
            rooms.clear();
            roomnoJLabel.setText("  1");
            
            //set border
            summaryJLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(251, 251, 251)));
            addBuildingLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
            
            //validate changes
            contentPanel.validate();
        }
    }//GEN-LAST:event_addBuildingLabelMouseClicked

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        if(nameJTextField.getText().isEmpty() || addressJTextField.getText().isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(addRoomPanel, "Required input can not be empty.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        try
        {
            building = new Building(nameJTextField.getText(), addressJTextField.getText(), landmarkJTextField1.getText(), landmarkJTextField2.getText(), landmarkJTextField3.getText()); 
        } catch(Exception exe)
        {
            javax.swing.JOptionPane.showMessageDialog(null, exe,"Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        homePanel.setVisible(false);
        addBuildingPanel.setVisible(false);
        addRoomPanel.setVisible(true);

        //validate changes
        contentPanel.validate();
    }//GEN-LAST:event_addJButtonActionPerformed
    
    //return the selected radiobutton
    public int getRoomType()throws Exception
    {
        if(jRadioButton1.isSelected())
            return 1;
        if(jRadioButton2.isSelected())
            return 2;
        if(jRadioButton3.isSelected())
            return 3;
        if(jRadioButton4.isSelected())
            return 4;
        
        throw new Exception();
    }
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Room lastRoom = new Room(Integer.parseInt(flatNoJTextField.getText()), Integer.parseInt(areaJTextField.getText()), Integer.parseInt(rentJTextField.getText()), getRoomType(), Integer.parseInt(bathroomJTextField.getText()), Integer.parseInt(maintenanceJTextField.getText()),Integer.parseInt(eleaccnoJTextField.getText()));
            rooms.add(lastRoom);
            
            //statement preparation for Building insertion
            String query = "INSERT INTO building (name, address, landmark1, landmark2, landmark3) "
                            + "VALUES( ?, ?, ?, ?, ?);";
            java.sql.PreparedStatement statement = conn.prepareStatement(query, java.sql.Statement.RETURN_GENERATED_KEYS);
            statement.setString(1, building.name);
            statement.setString(2, building.address);
            statement.setString(3, building.landmark1);
            statement.setString(4, building.landmark2);
            statement.setString(5, building.landmark3);
            
            //execute satement
            int affectedRows = statement.executeUpdate();
            if (affectedRows == 0) {
                throw new java.sql.SQLException("Building insertion failed!");
            }
            
            //building Foreign key for rooms
            int buildingID;
            try (java.sql.ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    buildingID = generatedKeys.getInt(1);
                    System.out.println(buildingID);
                }
                else {
                    throw new java.sql.SQLException("Building insertion failed, no ID obtained.");
                }
            }
            int roomNumber = 1;
            //add Rooms to Building
            for(Room room: rooms)
            {
                query = "INSERT INTO room (BuildingId, FlatNumber, Area, Rent, Bathrooms, Maintenance, ElectricityAccountNumber)"
                        + "VALUES (?, ?, ?, ?, ?, ? ,?)";
                statement = conn.prepareStatement(query);
                statement.setInt(1, buildingID);
                statement.setInt(2, room.flatNumber);
                statement.setInt(3, room.area);
                statement.setInt(4, room.rent);
                statement.setInt(5, room.bathrooms);
                statement.setInt(6, room.maintenance);
                statement.setInt(7, room.electricityAccountNumber);
                
                affectedRows = statement.executeUpdate();
                if (affectedRows == 0) {
                    throw new java.sql.SQLException("Room "+roomNumber+" insertion failed!");
                }
                
                roomNumber++;
            }
            //Pop-up message - Building successfully saved in database
            String message = building.name + " Building with "+ rooms.size() + " Rooms added to database successfully.";
            javax.swing.JOptionPane.showMessageDialog(addRoomPanel, message, "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            //clear all froms and go to summary page
            showSummaryPanel();
            
        }
        catch(Exception exe)
        {
            javax.swing.JOptionPane.showMessageDialog(addRoomPanel, "Failed to save in database.\n"+exe, "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveJButtonActionPerformed
    
    private void setRoomType(int type)
    {
        
        //reset Room type radiobutton
        typeButtonGroup.clearSelection();
        
        //set type button
        switch(type)
        {
            case 1:
                jRadioButton1.setSelected(true);
                break;
            case 2:
                jRadioButton2.setSelected(true);
                break;
            case 3:
                jRadioButton3.setSelected(true);
                break;
            case 4:
                jRadioButton4.setSelected(true);
        }
    }
    
    private void clearRoomForm()
    {
        //clear 
        flatNoJTextField.setText("");
        areaJTextField.setText("");
        rentJTextField.setText("");
        setRoomType( -1 );
        bathroomJTextField.setText("");
        maintenanceJTextField.setText("");
        eleaccnoJTextField.setText("");
    }
    
    private void nextJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Room lastRoom = new Room(Integer.parseInt(flatNoJTextField.getText()), Integer.parseInt(areaJTextField.getText()), Integer.parseInt(rentJTextField.getText()), getRoomType(), Integer.parseInt(bathroomJTextField.getText()), Integer.parseInt(maintenanceJTextField.getText()),Integer.parseInt(eleaccnoJTextField.getText()));
            rooms.add(lastRoom);
            clearRoomForm();
            
            //room number label
            roomnoJLabel.setText("  " + (rooms.size() + 1));
        }
        catch(Exception exe)
        {
            javax.swing.JOptionPane.showMessageDialog(addRoomPanel, "Missing/Invalid input."+exe, "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_nextJButtonActionPerformed
    
    private void preJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preJButtonActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(roomnoJLabel.getText().trim()) > 1)
        {
            //if current Room is already save in rooms list then remove
            if(Integer.parseInt(roomnoJLabel.getText().trim()) == rooms.size())
                rooms.remove(rooms.size() - 1);
             
            //set pre room value
            Room room = rooms.get(rooms.size() - 1);
            flatNoJTextField.setText(String.valueOf(room.flatNumber));
            areaJTextField.setText(String.valueOf(room.area));
            rentJTextField.setText(String.valueOf(room.rent));
            setRoomType(room.type);
            bathroomJTextField.setText(String.valueOf(room.bathrooms));
            maintenanceJTextField.setText(String.valueOf(room.maintenance));
            eleaccnoJTextField.setText(String.valueOf(room.electricityAccountNumber));
            
            //room number label and remove pre room from rooms list
            roomnoJLabel.setText("  " + rooms.size());
            rooms.remove(rooms.size() - 1);
        }
        else
        {
            homePanel.setVisible(false);
            addBuildingPanel.setVisible(true);
            addRoomPanel.setVisible(false);
            clearRoomForm();
            roomnoJLabel.setText("  1");
            
            //validate changes
            contentPanel.validate();
        }
    }//GEN-LAST:event_preJButtonActionPerformed

    //user defined variable
    private String PASSWORD;
    private String USERNAME;
    private String DATABASE;
    private String HOST;
    //database configuration values
    private com.mysql.jdbc.Connection conn;
    private Building building;
    private java.util.ArrayList<Room> rooms;
    private final javax.swing.ButtonGroup typeButtonGroup;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBuildingLabel;
    private javax.swing.JPanel addBuildingPanel;
    private javax.swing.JButton addJButton;
    private javax.swing.JPanel addRoomPanel;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JTextField areaJTextField;
    private javax.swing.JTextField bathroomJTextField;
    private javax.swing.JLabel buildingCountJLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTextField eleaccnoJTextField;
    private javax.swing.JTextField flatNoJTextField;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField landmarkJTextField1;
    private javax.swing.JTextField landmarkJTextField2;
    private javax.swing.JTextField landmarkJTextField3;
    private javax.swing.JTextField maintenanceJTextField;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JPanel navPanel;
    private javax.swing.JButton nextJButton;
    private javax.swing.JButton preJButton;
    private javax.swing.JTextField rentJTextField;
    private javax.swing.JLabel roomCountJLabel;
    private javax.swing.JLabel roomJLabel;
    private javax.swing.JLabel roomnoJLabel;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel summaryJLabel;
    // End of variables declaration//GEN-END:variables
}
